// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3_Cl6ebHSFlhug4oBPQMSfVFMsu5QUQ',
    appId: '1:849138072189:web:3f1426d0c70c1944308f14',
    messagingSenderId: '849138072189',
    projectId: 'darplus-c4763',
    authDomain: 'darplus-c4763.firebaseapp.com',
    storageBucket: 'darplus-c4763.firebasestorage.app',
    measurementId: 'G-3MDLNW3D3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAevDSpUAMeDu2xpIvvymqj3WJvkAEiR0',
    appId: '1:849138072189:android:2879eadff8f73314308f14',
    messagingSenderId: '849138072189',
    projectId: 'darplus-c4763',
    storageBucket: 'darplus-c4763.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJvUJBNZAO5YXnSVvaLn-MVzbYj4Nnizk',
    appId: '1:849138072189:ios:7313876a1f81129a308f14',
    messagingSenderId: '849138072189',
    projectId: 'darplus-c4763',
    storageBucket: 'darplus-c4763.firebasestorage.app',
    iosBundleId: 'com.msg.dar.plus.darPlusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJvUJBNZAO5YXnSVvaLn-MVzbYj4Nnizk',
    appId: '1:849138072189:ios:7313876a1f81129a308f14',
    messagingSenderId: '849138072189',
    projectId: 'darplus-c4763',
    storageBucket: 'darplus-c4763.firebasestorage.app',
    iosBundleId: 'com.msg.dar.plus.darPlusApp',
  );
}
